"""empty message

Revision ID: 2567335e3024
Revises: 34761fce13d9
Create Date: 2023-06-13 15:30:05.046518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2567335e3024'
down_revision = '34761fce13d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technician', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=250), nullable=True))
        batch_op.create_unique_constraint(None, ['avatar'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('technician', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
