"""empty message

Revision ID: 34761fce13d9
Revises: fbb4bd4b22f9
Create Date: 2023-06-12 14:50:23.599195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34761fce13d9'
down_revision = 'fbb4bd4b22f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.String(length=250), nullable=True))
        batch_op.create_unique_constraint(None, ['avatar'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farmer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###
